version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: truck_snack_db
    ports:
      - "3400:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=truck_snack_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=1234
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    restart: always
    volumes:
      - /Users/Shared/data/mysql-test:/var/lib/mysql